name: gasport

on:
  workflow_dispatch

jobs:
  export:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: croconut/godot-multi-builder@v1
        id: builds
        with:
          names: "Android"

      - uses: actions/upload-artifact@v1
        with:
          name: my-builds
          path: builds/builds.zip